version: "3.9"


services:
  database: 
    build: ./database
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    networks:
      - spring_net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  backend:
    build: ./backend
    container_name: backend
    platform: linux/amd64
    ports:
      - "8080:8080"
    restart: always
    networks:
      - spring_net
    depends_on:
      database:
        condition: service_healthy
    
networks:
  spring_net: